#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : wayland
Version  : 1.11.0
Release  : 1
URL      : https://wayland.freedesktop.org/releases/wayland-1.11.0.tar.xz
Source0  : https://wayland.freedesktop.org/releases/wayland-1.11.0.tar.xz
Summary  : Wayland cursor helper library
Group    : Development/Tools
License  : MIT
Requires: wayland-bin
Requires: wayland-lib
Requires: wayland-data
BuildRequires : docbook-xml
BuildRequires : doxygen
BuildRequires : graphviz
BuildRequires : grep
BuildRequires : libxslt
BuildRequires : pkgconfig(expat)
BuildRequires : pkgconfig(libffi)
BuildRequires : pkgconfig(libxml-2.0)
BuildRequires : xmlto

%description
What is Wayland?
Wayland is a project to define a protocol for a compositor to talk to
its clients as well as a library implementation of the protocol.  The
compositor can be a standalone display server running on Linux kernel
modesetting and evdev input devices, an X application, or a wayland
client itself.  The clients can be traditional applications, X servers
(rootless or fullscreen) or other display servers.

%package bin
Summary: bin components for the wayland package.
Group: Binaries
Requires: wayland-data

%description bin
bin components for the wayland package.


%package data
Summary: data components for the wayland package.
Group: Data

%description data
data components for the wayland package.


%package dev
Summary: dev components for the wayland package.
Group: Development
Requires: wayland-lib
Requires: wayland-bin
Requires: wayland-data
Provides: wayland-devel

%description dev
dev components for the wayland package.


%package lib
Summary: lib components for the wayland package.
Group: Libraries
Requires: wayland-data

%description lib
lib components for the wayland package.


%prep
%setup -q -n wayland-1.11.0

%build
export LANG=C
%configure --disable-static --disable-documentation
make V=1  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/wayland-scanner

%files data
%defattr(-,root,root,-)
/usr/share/wayland/wayland-scanner.mk
/usr/share/wayland/wayland.dtd
/usr/share/wayland/wayland.xml

%files dev
%defattr(-,root,root,-)
/usr/include/*.h
/usr/lib64/*.so
/usr/lib64/pkgconfig/*.pc
/usr/share/aclocal/*.m4

%files lib
%defattr(-,root,root,-)
/usr/lib64/*.so.*
